easy_admin:
    entities:
        User:
            class: SN\UserBundle\Entity\User
            label: 'Users'
            form:
                fields: ['enabled', 'username', 'email', 'roles', 'lastLogin']