---

- name: Nginx vhost for {{ item.name }}
  become: yes
  template: src=templates/site.j2 dest=/etc/nginx/sites-available/{{ item.name }}.conf owner=root group=root mode=644
  with_items: "{{ nginx_sites }}"

- name: Nginx enable vhost
  become: yes
  file: src=/etc/nginx/sites-available/{{ item.name }}.conf dest=/etc/nginx/sites-enabled/{{ item.name }}.conf state=link
  with_items: "{{ nginx_sites }}"

- name: restart nginx
  become: yes
  service: name=nginx state=restarted
...