---

- name: install redis and redis tools
  become: yes
  apt: name="{{ item }}" state="latest" update_cache=yes
  become: yes
  tags: php
  with_items: 
    - redis-server
    - redis-tools
    - php5-redis
    
...