sn_core_homepage:
    path:     /
    defaults: { _controller: SNCoreBundle:Default:index }
sn_core_back:
    path: /back
    defaults: { _controller: SNCoreBundle:Back:index }

sn_core_donate:
    path: /donate
    defaults: { _controller: SNCoreBundle:Back:donate }