sn_user_homepage:
    path:     /
    defaults: { _controller: SNUserBundle:Default:index }

sn_user_view:
    path: /view/
    defaults: { _controller: SNUserBundle:Default:view }

sn_user_edit:
    path: /edit/{id}
    defaults: { _controller: SNUserBundle:Default:edit }

sn_user_delete:
    path: /delete/{id}
    defaults: { _controller: SNUserBundle:Default:delete }

sn_user_changeRole:
    path: /changeRole/
    defaults: { _controller: SNUserBundle:Default:changeRole }

sn_user_changePassword:
    path: /changePassword/{id}
    defaults : { _controller: SNUserBundle:Default:changePassword}