sn_link_homepage:
    path:     /
    defaults: { _controller: SNLinkBundle:Default:index }

sn_link_add:
    path:     /back/add/
    defaults: { _controller: SNLinkBundle:Default:add }

sn_link_view:
    path:     /back/view/
    defaults: { _controller: SNLinkBundle:Default:view }

sn_link_delete:
    path:     /back/delete/{id}
    defaults: { _controller: SNLinkBundle:Default:delete }

sn_link_edit:
    path:     /back/edit/{id}
    defaults: { _controller: SNLinkBundle:Default:edit }